# version: 2021.12.19
# author: Martin Kraemer, mk.maddin@gmail.com
# description: YAML configuration file - holding predefined entities
#   see: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md

sensor:

#  - source: <property / attribute / namespacelist>
#    id: <name of the charger attribute or prop to read>
#    name: <optional: name of the sensor within HA>
#    uid: <optional: unique ID postfix - required if mutliple entities wiht same <id> value exist>
#    description: <optional: key within HA>
#    icon: <optional: key within HA>
#    enabled: <optional: if set to False entity is by default disabled>
#    device_class: <optional: key within HA>
#    state_class: <optional: key within HA>
#    unit_of_measurement: <optional: key within HA>
#    entity_category: <optional: key within HA>
#    value_id: <required for charger properties of type namespace: define which namespace attribute should be used as state value>
#    namespace_id: <required for namespacelist source objects: define which item from the list of namespaces should be used>
#    attribute_ids: <optional for charger properties of type namespace: define which namespace attributes should be included into HA> 
#    enum: <optional dict to map states to enum values>

  - source: attribute
    id: AccessState
    description: "State of access for the charger - values are: 'open', 'locked', 'auto'"
    icon: "mdi:lock-question"

  - source: attribute
    id: carConnected
    description: "State of the car plug - values are: 'no car', 'charging', 'ready','complete'"
    icon: "mdi:ev-plug-type2"

  - source: namespacelist
    id: cards_0
    name: "ID Chip 0"
    description: "charging ID chip/card 0 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 0
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_1
    name: "ID Chip 1"
    description: "charging ID chip/card 1 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 1
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_2
    name: "ID Chip 2"
    description: "charging ID chip/card 2 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 2
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_3
    name: "ID Chip 3"
    description: "charging ID chip/card 3 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 3
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_4
    name: "ID Chip 4"
    description: "charging ID chip/card 4 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 4
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_5
    name: "ID Chip 5"
    description: "charging ID chip/card 5 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 5
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_6
    name: "ID Chip 6"
    description: "charging ID chip/card 6 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 6
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_7
    name: "ID Chip 7"
    description: "charging ID chip/card 7 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 7
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_8
    name: "ID Chip 8"
    description: "charging ID chip/card 8 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 8
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_9
    name: "ID Chip 9"
    description: "charging ID chip/card 9 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    enabled: False
    value_id: energy
    namespace_id: 9
    attribute_ids:
      - name
      - cardId

#  - source: attribute
#    id: errorState
#    name: ChargingState
#    description: "Charging state of the car - values are: 'Unknown Error', 'Idle', 'Charging', 'Wait Car', 'Complete', 'Error'"
#    icon: "mdi:state-machine"
#    enabled: False

  - source: property
    id: car
    name: CarState
    enum:
      0: "Unknown"
      1: "Idle"
      2: "Charging"
      3: "Wait Car"
      4: "Complete"
      5: "Error"
    description: "Charging state of the car - values are: 'Unknown', 'Idle', 'Charging', 'Wait Car', 'Complete', 'Error'"
    icon: "mdi:state-machine"

  - source: property
    id: cci
    name: "Inverter"
    description: "Connected solar inverter"
    icon: "mdi:solar-power"
    entity_category: diagnostic
    value_id: label
    attribute_ids:
      - paired
      - model
      - commonName
      - ip
      - connected
      - status
      - message

  - source: property
    id: ccw 
    name: "WiFi Connection"
    description: "WiFi connection information"
    icon: "mdi:wifi"
    entity_category: diagnostic
    value_id: ssid
    attribute_ids:
      - ip
      - netmask
      - gw
      - channel
      - bssid

  - source: property
    id: cus
    name: CableUnlock
    enum:
      0: "Unknown"
      1: "Unlocked"
      2: "UnlockFailed"
      3: "Locked"
      4: "LockFailed"
      5: "LockUnlockPowerout"
    description: "Cable unlock status - values are: 'Unknown', 'Unlocked', 'UnlockFailed', 'Locked', 'LockFailed', 'LockUnlockPowerout'"
    icon: "mdi:state-machine"
    entity_category: diagnostic

  - source: property
    id: err
    name: "InternalError"
    enum:
      0: "None"
      1: "FiAc"
      2: "FiDc"
      3: "Phase"
      4: "Overvolt"
      5: "Overamp"
      6: "Diode"
      7: "PpInvalid"
      8: "GndInvalid"
      9: "ContactorStuck"
      10: "ContactorMiss"
      11: "FiUnknown"
      12: "Unknown"
      13: "Overtemp"
      14: "NoComm"
      15: "StatusLockStuckOpen"
      16: "StatusLockStuckLocked"
      20: "Reserved20"
      21: "Reserved21"
      22: "Reserved22"
      23: "Reserved23"
      24: "Reserved24"
    description: "Internal error state - values are: 'None', 'FiAc', 'FiDc', 'Phase', 'Overvolt', 'Overamp', 'Diode', 'PpInvalid', 'GndInvalid', 'ContactorStuck', 'ContactorMiss', 'FiUnknown', 'Unknown', 'Overtemp', 'NoComm', 'StatusLockStuckOpen', 'StatusLockStuckLocked', 'Reserved20', 'Reserved21', 'Reserved22', 'Reserved23', 'Reserved24'"
    icon: "mdi:alert-circle"
    entity_category: diagnostic

  - source: property
    id: eto
    name: "Totally Charged"
    description: "Totally charged power"
    #icon: "mdi:meter-electric" #not available (yet)
    icon: "mdi:ev-station"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    #entity_category: diagnostic

  - source: property
    id: ffb
    name: "Lock Feedback"
    enum:
      0: "Unknown"
      1: "Unlocked"
      2: "UnlockFailed"
      3: "Locked"
      4: "LockFailed"
      5: "LockUnlockPowerout"      
    description: "Actual lock feedback - values are: 'Unknown', 'Unlocked', 'UnlockFailed', 'Locked', 'LockFailed', 'LockUnlockPowerout'"
    icon: "mdi:lock-reset"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: lck
    name: "Effective lock setting"
    enum:
      0: "Normal"
      1: "AutoUnlock"
      2: "AlwaysLock"
      3: "ForceUnlock"
    description: "Lock setting, as sent to Charge Ctrl - values are: 'Normal', 'AutoUnlock', 'AlwaysLock', 'ForceUnlock'"
    icon: "mdi:lock"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: loc
    name: "Local Time"
    description: "Local time on the charger"
    icon: "mdi:clock-outline"
    enabled: False
    device_class: timestamp
    entity_category: diagnostic

  - source: property
    id: modelStatus
    name: "ChargingReason"
    enum:
      0: "NotChargingBecauseNoChargeCtrlData"
      1: "NotChargingBecauseOvertemperature"
      2: "NotChargingBecauseAccessControlWait"
      3: "ChargingBecauseForceStateOn"
      4: "NotChargingBecauseForceStateOff"
      5: "NotChargingBecauseScheduler"
      6: "NotChargingBecauseEnergyLimit"
      7: "ChargingBecauseAwattarPriceLow"
      8: "ChargingBecauseAutomaticStopTestLadung"
      9: "ChargingBecauseAutomaticStopNotEnoughTime"
      10: "ChargingBecauseAutomaticStop"
      11: "ChargingBecauseAutomaticStopNoClock"
      12: "ChargingBecausePvSurplus"
      13: "ChargingBecauseFallbackGoEDefault"
      14: "ChargingBecauseFallbackGoEScheduler"
      15: "ChargingBecauseFallbackDefault"
      16: "NotChargingBecauseFallbackGoEAwattar"
      17: "NotChargingBecauseFallbackAwattar"
      18: "NotChargingBecauseFallbackAutomaticStop"
      19: "ChargingBecauseCarCompatibilityKeepAlive"
      20: "ChargingBecauseChargePauseNotAllowed"
      22: "NotChargingBecauseSimulateUnplugging"
      23: "NotChargingBecausePhaseSwitch"
      24: "NotChargingBecauseMinPauseDuration"      
    description: "Reason why we allow charging or not right now - values are listed at: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md -> modelStatus"
    icon: "mdi:ev-station"
    entity_category: diagnostic

  - source: property
    id: nrg
    name: "Charging Energy"
    description: "Charging energy used for current car charging process"
    icon: "mdi:lightning-bolt-circle"
    device_class: power
    unit_of_measurement: W
    value_id: 11
    attribute_ids:
      - L1_Voltage:0
      - L2_Voltage:1
      - L3_Voltage:2
      - N_Voltage:3
      - L1_Ampere:4
      - L2_Ampere:5
      - L3_Ampere:6
      - L1_Power:7
      - L2_Power:8
      - L3_Power:9
      - N_Power:10
      - TotalPower:11
      - L1_PowerRelative:12
      - L2_PowerRelative:13
      - L3_PowerRelative:14
      - N_PowerRelative:15

  - source: property
    id: qsw
    name: "Webserver Queue"
    description: "Queue size webserver/websocket"
    icon: "mdi:web-sync"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: rbc
    name: "Reboot Counter"
    description: "Counts the number of boot operations."
    icon: "mdi:restart"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: rbt
    name: "Reboot Timer"
    description: "Counts the milliseconds since the last boot. Expires after 49 days, increasing the reboot_counter."
    icon: "mdi:av-time"
    enabled: False
    unit_of_measurement: "ms"
    entity_category: diagnostic

  - source: property
    id: rssi
    name: "WiFi Signal"
    description: "Signal strength of the connected WiFi"
    icon: "mdi:wifi"
    enabled: False
    device_class: signal_strength
    unit_of_measurement: "dB"
    entity_category: diagnostic

  - source: property
    id: tma
    name: "Charger Temp"
    description: "Temperature of the controller"
    icon: "mdi:thermometer"
    device_class: temperature
    unit_of_measurement: "°C"
    entity_category: diagnostic

  - source: property
    id: wcch
    name: "HTTP Clients"
    description: "Webserver connected clients as HTTP"
    icon: "mdi:web-box"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: wccw
    name: "WEBSOCKET Clients"
    description: "Webserver connected clients as WEBSOCKET"
    icon: "mdi:web-box"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: wh
    name: "Connection Charged"
    description: "Energy in Wh since car connected"
    #icon: "mdi:meter-electric-outline" # not available (yet)
    icon: "mdi:ev-station"
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: "Wh"

  - source: property
    id: wst
    name: WifiState
    enum:
      0: "IDLE_STATUS"
      1: "NO_SSID_AVAIL"
      2: "SCAN_COMPLETED"
      3: "CONNECTED"
      4: "CONNECT_FAILED"
      5: "CONNECTION_LOST"
      6: "DISCONNECTED"
      8: "CONNECTING"
      9: "DISCONNECTING"
      10: "NO_SHIELD"      
    description: "WiFi status - values are: 'IDLE_STATUS', 'NO_SSID_AVAIL', 'SCAN_COMPLETED', 'CONNECTED', 'CONNECT_FAILED', 'CONNECTION_LOST', 'DISCONNECTED', 'CONNECTING', 'DISCONNECTING', 'NO_SHIELD'"
    icon: "mdi:wifi-settings"
    enabled: False
    entity_category: diagnostic

